### ISSUE TITLE
Icon Request: Otter Browser

### ISSUE THREAD

**Issue by mkljczk** [sonakinci41/DamaDamas-icon-theme#1]
- [Otter Browser](https://github.com/OtterBrowser/otter-browser)
- Project that aims to recreate the best aspects of the classic Opera (12.x) UI using Qt5
- `Icon=otter-browser`
![10384419](https://cloud.githubusercontent.com/assets/21127288/24331480/9c76167e-1235-11e7-9012-0a64312e877f.png)
Thanks for making this really good theme ;)

**Comment by sonakinci41** [comment]
I'm glad you liked the theme. I've drawn an icon for otter-browser and added it to the theme. Thank you.(Translate)

**Comment by mthnzbk** [comment]
221d8571391739811efbcebe483fba655565ac30

**Comment by mkljczk** [comment]
thanks, it looks really nice :)
