### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by mmetak** [sonakinci41/DamaDamas-icon-theme#3]
The spaces in two icon names in `apps/scalable` crash the gtk-update-cache.
`Angry Birds-chrome.angrybirds.com.svg` & `unity-control-center screen.svg`

**Comment by sonakinci41** [comment]
461374ecd4a6754bf98ed1f22f6f4bc350dcfa8d thanks for issue
