### ISSUE TITLE
Icon Request: ClipIt tray icon

### ISSUE THREAD

**Issue by Vistaus** [sonakinci41/DamaDamas-icon-theme#4]
It would be great to have a monochrome tray icon for ClipIt :)

**Comment by sonakinci41** [comment]
d38ad8a0f91777a948531ee75c2cd3105aee799f
Thanks for the issues. I added the icons I hope you like. The icons may not be correct because the applications are not installed by me. Please note that if you do not see the icons.

**Comment by Vistaus** [comment]
They both look great, thank you so much! :) (and they are correct!)
