### ISSUE TITLE
What does the installer do?

### ISSUE THREAD

**Issue by roelofr** [sonakinci41/DamaDamas-icon-theme#7]
#I was looking at the python script ([`damadamas-installer.py`](https://github.com/sonakinci41/DamaDamas-icon-theme/blob/master/damadamas-installer.py)), but find it very hard to decide what it does, partly because most of the code is in a foreign language I can't place.

Could you maybe explain what it does, or how to manually perform the steps the script performs?

I'd love to hear a reply.

Cheers!

**Comment by sonakinci41** [comment]
Yes, I have not made any effort to make the file understandable. A slice of code with its own slice. It is necessary to make the code understandable when I am available. Basically the code is doing 2 things.
1) The files are rsync-related directory based on your selections. So if you choose the horizontal icons, it is assumed that you do not select the vertical directory.
2) It changes the colors in the files being moved. To do this, open each svg file and look for the predefined color and replace it with the color the user chooses or enters by hand.
It was translated with Google Translate. I hope it's clear.

**Comment by sonakinci41** [comment]
ccd182a62194c508154978a0c8198c25114dcb09 I hope that will be useful
